[project]
name = "intern_manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.10.1",
    "ruff>=0.14.9",
]
[tool.pytest.ini_options]
pythonpath = ["src"]
